title: TERABYTE
description: 테라의 각종 저장소
theme: just-the-docs

url: https://ne-eun.github.io
aux_links:
  TERA's Repository: https://github.com/ne-eun

callouts:
  highlight:
    color: purple
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red